hotfix/SUIT-16698
SuitestAutomation/suitest-js-api pull request #354
Opened 2021-02-26 16:34 UTC by Noorama

2021-03-01 08:33 UTC, JeKachan requested changes

2021-03-01 08:33 UTC, JeKachan commented on lib/utils/translateResults.js
> +const titleDescToText = result => result.description && result.description.value
@Noorama please, use `toText` function from @suitest/smst-to-text package for proper translating title and description

2021-03-01 11:41 UTC, JeKachan approved these changes

2021-03-02 10:18 UTC, andriichumak commented on lib/utils/translateResults.js
> +	return `${titleResult}`;
Minor thing, but you don't really need string interpolation here. Just `return titleResult`.

2021-03-02 10:19 UTC, andriichumak approved these changes

2021-03-02 10:19 UTC, merged