SUIT-18496 - recording option was added to pairDevice attributes. startRecording and stopRecording were added.
SuitestAutomation/suitest-js-api pull request #493
Opened 2023-01-30 11:09 UTC by Noorama

2023-01-31 09:21 UTC, JeKachan requested changes

2023-01-31 09:21 UTC, JeKachan commented on lib/commands/pairDevice.js
> +	recording = 'none',
I would combine `recording` and `webhookUrl` parameters into object parameters. It will help add additional options in future

2023-01-31 09:21 UTC, JeKachan commented on lib/commands/startRecording.js
> + * @param {Object} instance of main class
please use `SUITEST_API` instead of `Object`

2023-01-31 09:21 UTC, JeKachan commented on lib/commands/stopRecording.js
> + * @param {Object} instance of main class
`Object` -> `SUITEST_API`

2023-02-06 16:04 UTC, JeKachan requested changes

2023-02-07 08:09 UTC, Noorama commented on lib/commands/stopRecording.js
> +async function stopRecording({webSockets, authContext, logger}, webhookSettings) {
This is specifications which was given by BE

2023-02-07 09:40 UTC, JeKachan approved these changes

2023-02-07 09:40 UTC, merged